# docker-composeversion: '3.3'

services:
  postgres:
    image: postgres:16.0-alpine
    container_name: 'postgres_fox'
    volumes:
      - postgre_db_fox:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  bot:
    container_name: 'bot_fox'
    build: ./bot
    env_file:
      - .env
    volumes:
      - file_storage:/fox_test/file_storage
    depends_on:
      - postgres
    restart: on-failure

  backend:
    container_name: 'backend_fox'
    build: ./backend
    env_file:
      - .env
    volumes:
      - file_storage:/fox_test/file_storage
    command: gunicorn main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    depends_on:
      - bot
    restart: on-failure

  nginx:
    image: nginx:latest
    container_name: 'nginx_fox'
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infra/nginx/configs:/etc/nginx/conf.d:ro
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  postgre_db_fox:
  file_storage: